name:                euclid-proof-checker
version:             0.1.0.0
github:              "jorpic/euclid-proof-checker"
license:             BSD3
author:              "Max Taldykin"
maintainer:          "jorpic@gmail.com"
copyright:           "2022 Max Taldykin"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jorpic/euclid-proof-checker#readme>

dependencies:
- base >= 4.7 && < 5

default-extensions:
  - ImportQualifiedPost
  - LambdaCase
  - OverloadedStrings
  - RecordWildCards

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - text
  - megaparsec
  - containers

executables:
  euclid-proof-checker:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - euclid-proof-checker
    - containers
    - filepath
    - text

tests:
  euclid-proof-checker-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - euclid-proof-checker
    - containers
    - hspec
    - hspec-megaparsec
    - megaparsec
    - neat-interpolation
    - text
